#!/usr/bin/env python3
"""Generates src/info.rs and src/sounds.rs from the original C sources.

info.c is ~4700 lines of data tables (states, mobj types, sprite
names); transcribing them by hand would be error-prone, so this reads
the original info.h/info.c/sounds.h and emits the Rust tables
mechanically, keeping every value and every per-entry comment.

Usage: tools/gen_info.py [path/to/DoomMetal/src]
(default: ../DoomMetal/src relative to the repository root)
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "..", "DoomMetal", "src")


def read(name):
    with open(os.path.join(SRC, name)) as f:
        return f.read()


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def c_enum(header, last):
    """Identifiers of the C enum whose final member is `last`, in order
    (excluding `last` itself, the count)."""
    body = strip_comments(header)
    end = body.index(last)
    start = body.rindex("{", 0, end)
    names = [n.strip() for n in body[start + 1 : end].split(",")]
    names = [n for n in names if n]
    for n in names:
        assert re.fullmatch(r"[A-Za-z_]\w*", n), n
    return names


def camel(name):
    """The port's convention for C enum members: keep the prefix,
    CamelCase each `_`-separated part (`wp_supershotgun` ->
    `WpSupershotgun`, `S_POSS_STND2` -> `SPossStnd2`); parts already in
    mixed case keep it (`A_FaceTarget` -> `AFaceTarget`)."""
    out = ""
    for part in name.split("_"):
        if not part:
            continue
        rest = part[1:].lower() if part.isupper() or part.islower() else part[1:]
        out += part[0].upper() + rest
    return out


def variants(names):
    out = [camel(n) for n in names]
    assert len(set(out)) == len(out), "CamelCase collision"
    return out


def expr(value, sprites, states, sfx):
    """Translates one C initializer expression to Rust."""
    def tok(m):
        t = m.group(0)
        if t.startswith("MF_"):
            return "mobj_flag::" + t[3:]
        if t == "FRACUNIT":
            return "FRACUNIT"
        if t in states:
            return "StateNum::" + camel(t)
        if t in sfx:
            return "Sfx::" + camel(t)
        if t in sprites:
            return "SpriteNum::" + camel(t)
        raise ValueError("unknown token " + t)

    return re.sub(r"[A-Za-z_]\w*", tok, value.strip())


def enum_block(doc, name, members, extra_derive=""):
    lines = [doc, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash%s)]" % extra_derive]
    lines += ["#[allow(clippy::enum_variant_names)]", "pub enum %s {" % name]
    for c, r in members:
        lines.append("    /// `%s`" % c)
        lines.append("    %s," % r)
    lines.append("}")
    return "\n".join(lines)


GENERATED = "// GENERATED by tools/gen_info.py from the original %s — do not edit by hand.\n"


def gen_sound_tables(sfx, music):
    """`S_sfx`/`S_music` from sounds.c. Only the static fields of
    `sfxinfo_t`/`musicinfo_t`; the runtime ones (`data`, `usefulness`,
    `lumpnum`, `handle`) live in s_sound.rs's state."""
    c = strip_comments(read("sounds.c"))
    m_body = c[c.index("S_music[]") :]
    m_body = m_body[: m_body.index("};")]
    names = re.findall(r'\{\s*("[^"]*"|0)\s*(?:,\s*0\s*)?\}', m_body)
    assert len(names) == len(music), (len(names), len(music))
    s_body = c[c.index("S_sfx[]") :]
    s_body = s_body[: s_body.index("};")]
    ent = re.findall(
        r'\{\s*"(\w+)"\s*,\s*(true|false)\s*,\s*(-?\d+)\s*,\s*(0|&S_sfx\[(\w+)\])\s*,'
        r"\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*0\s*\}",
        s_body,
    )
    assert len(ent) == len(sfx), (len(ent), len(sfx))
    out = [
        "\n/// Static half of `sfxinfo_t` (`sounds.c`'s `S_sfx[]`). The runtime",
        "/// fields (`data`, `usefulness`, `lumpnum`) live in `s_sound.rs`.",
        "#[derive(Debug, Clone, Copy)]",
        "pub struct SfxInfo {",
        "    /// Up to 6-character name (lump is `ds<name>`).",
        "    pub name: &'static str,",
        "    /// Only one at a time.",
        "    pub singularity: bool,",
        "    pub priority: i32,",
        "    /// Referenced sound if a link.",
        "    pub link: Option<Sfx>,",
        "    /// Pitch if a link.",
        "    pub pitch: i32,",
        "    /// Volume if a link.",
        "    pub volume: i32,",
        "}",
        "",
        "/// `S_sfx[]`.",
        "pub static S_SFX: [SfxInfo; NUMSFX] = [",
    ]
    for name, sing, prio, _l, link, pitch, vol in ent:
        out.append(
            "    SfxInfo { name: %s, singularity: %s, priority: %s, link: %s, pitch: %s, volume: %s },"
            % (
                '"%s"' % name,
                sing,
                prio,
                "Some(Sfx::%s)" % camel(link) if link else "None",
                pitch,
                vol,
            )
        )
    out.append("];")
    out += [
        "",
        "/// `S_music[]`: lump name is `d_<name>`; `mus_None` has none.",
        "pub static S_MUSIC: [Option<&str>; NUMMUSIC] = [",
    ]
    for n in names:
        out.append("    %s," % ("None" if n == "0" else "Some(%s)" % n))
    out.append("];")
    return "\n".join(out) + "\n"


def gen_sounds():
    h = read("sounds.h")
    music = c_enum(h, "NUMMUSIC")
    sfx = c_enum(h, "NUMSFX")
    out = [
        GENERATED % "sounds.h",
        """//! Port of `sounds.h` (enums only). Created by BIFFO — the
//! original's own description of `sounds.h`.
//!
//! # Scope
//!
//! `musicenum_t`/`sfxenum_t` (which `info.rs`'s mobj table refers to)
//! plus the static `S_sfx`/`S_music` tables from `sounds.c`.
//!
//! Variants keep the original's `mus_`/`sfx_` prefixes, same convention
//! as `doomdef.rs`'s enums.
""",
        "/// (`NUMMUSIC`)\npub const NUMMUSIC: usize = %d;\n" % len(music),
        enum_block(
            "/// Identifiers for all music in game (`musicenum_t`).",
            "MusicEnum",
            zip(music, variants(music)),
        ),
        "\n/// (`NUMSFX`)\npub const NUMSFX: usize = %d;\n" % len(sfx),
        enum_block(
            "/// Identifiers for all sfx in game (`sfxenum_t`).",
            "Sfx",
            zip(sfx, variants(sfx)),
        ),
        "\nimpl Sfx {\n    /// Every sfx in enum order, so `sfx_posit1 + n`-style arithmetic can\n    /// be done as `Sfx::from_index(Sfx::SfxPosit1 as usize + n)`.\n    pub const ALL: [Sfx; NUMSFX] = [\n"
        + "".join("        Sfx::%s,\n" % v for v in variants(sfx))
        + "    ];\n\n    /// `sfxenum_t` from its integer value.\n    pub fn from_index(i: usize) -> Sfx {\n        Self::ALL[i]\n    }\n}\n",
        gen_sound_tables(sfx, music),
        """
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enum_sizes_match_original_counts() {
        assert_eq!(MusicEnum::MusNone as usize, 0);
        assert_eq!(Sfx::SfxNone as usize, 0);
        assert_eq!(Sfx::%s as usize, NUMSFX - 1);
        assert_eq!(MusicEnum::%s as usize, NUMMUSIC - 1);
    }

    #[test]
    fn sound_tables_match_sounds_c() {
        assert_eq!(S_SFX[Sfx::SfxPistol as usize].name, "pistol");
        assert_eq!(S_SFX[Sfx::SfxSawidl as usize].priority, 118);
        assert!(S_SFX[Sfx::SfxItemup as usize].singularity);
        let chgun = &S_SFX[Sfx::SfxChgun as usize];
        assert_eq!((chgun.link, chgun.pitch), (Some(Sfx::SfxPistol), 150));
        assert!(S_SFX[Sfx::SfxPistol as usize].link.is_none());
        assert_eq!(S_MUSIC[MusicEnum::MusNone as usize], None);
        assert_eq!(S_MUSIC[MusicEnum::MusE1m1 as usize], Some("e1m1"));
    }
}
"""
        % (camel(sfx[-1]), camel(music[-1])),
    ]
    return "\n".join(out), set(sfx)


def gen_info(sfx):
    h = read("info.h")
    c = read("info.c")
    sprites = c_enum(h, "NUMSPRITES")
    states = c_enum(h, "NUMSTATES")
    mobjtypes = c_enum(h, "NUMMOBJTYPES")

    # sprnames[]
    body = c[c.index("char *sprnames[NUMSPRITES]") :]
    body = body[body.index("{") + 1 : body.index("};")]
    sprnames = re.findall(r'"(\w+)"', body)
    assert len(sprnames) == len(sprites)
    for n, s in zip(sprnames, sprites):
        assert s == "SPR_" + n, (s, n)

    # states[]
    body = c[c.index("state_t\tstates[NUMSTATES]") :]
    body = body[body.index("{") + 1 : body.index("\n};")]
    state_rows = re.findall(
        r"^\s*\{(SPR_\w+),(-?\d+),(-?\d+),\{(\w+)\},(S_\w+),(-?\d+),(-?\d+)\},?\s*//\s*(S_\w+)\s*$",
        body,
        re.M,
    )
    assert len(state_rows) == len(states), (len(state_rows), len(states))
    for row, name in zip(state_rows, states):
        assert row[7] == name, (row[7], name)
    actions = sorted({r[3] for r in state_rows} - {"NULL"})

    # mobjinfo[]
    body = c[c.index("mobjinfo_t mobjinfo[NUMMOBJTYPES]") :]
    body = body[body.index("{") + 1 :]
    entries = re.split(r"\n    \{\s*// ", body)[1:]
    assert len(entries) == len(mobjtypes)
    fields = [
        "doomednum", "spawnstate", "spawnhealth", "seestate", "seesound",
        "reactiontime", "attacksound", "painstate", "painchance", "painsound",
        "meleestate", "missilestate", "deathstate", "xdeathstate", "deathsound",
        "speed", "radius", "height", "mass", "damage", "activesound", "flags",
        "raisestate",
    ]
    infos = []
    for entry, mt in zip(entries, mobjtypes):
        assert entry.split("\n")[0].strip() == mt, (entry[:40], mt)
        vals = dict(
            (f, v.strip())
            for v, f in re.findall(r"^\s*([^/\n]+?),?\s*//\s*(\w+)\s*$", entry, re.M)
        )
        assert list(vals) == fields, (mt, list(vals))
        infos.append((mt, vals))

    sset, sfxset, sprset = set(states), sfx, set(sprites)
    state_fields = {f for f in fields if f.endswith("state")}
    sound_fields = {f for f in fields if f.endswith("sound")}

    def tr(field, v):
        # The C table sometimes writes a plain 0 in a state/sound field
        # (the fields are `int`); for the typed Rust fields that's the
        # enum member with value 0.
        if v == "0" and field in state_fields:
            return "StateNum::SNull"
        if v == "0" and field in sound_fields:
            return "Sfx::SfxNone"
        out = expr(v, sprset, sset, sfxset)
        if field in state_fields:
            assert out.startswith("StateNum::"), (field, v)
        if field in sound_fields:
            assert out.startswith("Sfx::"), (field, v)
        return out

    out = [GENERATED % "info.h/info.c"]
    out.append(
        """//! Port of `info.h` / `info.c` (Phase 6a). Thing frame/state LUT,
//! generated by `multigen` utility (the original's own description) —
//! and generated again here, by `tools/gen_info.py`, from the original
//! C tables.
//!
//! # Representation choices
//!
//! Enum members keep their C prefixes (`SPR_`, `S_`, `MT_`), CamelCased
//! like the rest of the port (`S_POSS_STND2` → `StateNum::SPossStnd2`).
//! [`MobjInfo`]'s state/sound fields (plain `int` in the original) are
//! typed as [`StateNum`]/[`Sfx`]; the numeric values are the same
//! (`S_NULL`/`sfx_None` are 0).
//!
//! `state_t.action` is an `actionf_t` function pointer to an `A_*`
//! routine in `p_enemy.c`/`p_pspr.c`, none of which exist yet. A static
//! table can't hold pointers to them, so it becomes [`StateAction`], one
//! variant per `A_*` function (and `None` for `{NULL}`); the code that
//! runs states (`P_SetMobjState`, `P_SetPsprite`, later phases)
//! dispatches on it with a `match`, as `d_think.rs`'s docs anticipated.
"""
    )
    out.append(
        "use crate::m_fixed::{Fixed, FRACUNIT};\nuse crate::r_defs::mobj_flag;\nuse crate::sounds::Sfx;\n"
    )

    out.append("/// (`NUMSPRITES`)\npub const NUMSPRITES: usize = %d;\n" % len(sprites))
    out.append(enum_block("/// (`spritenum_t`)", "SpriteNum", zip(sprites, variants(sprites))))
    out.append("\n/// (`sprnames[NUMSPRITES]`) — indexed by [`SpriteNum`].\n#[rustfmt::skip]")
    out.append("pub const SPRNAMES: [&str; NUMSPRITES] = [")
    for i in range(0, len(sprnames), 10):
        out.append("    " + " ".join('"%s",' % n for n in sprnames[i : i + 10]))
    out.append("];\n")

    out.append("/// (`NUMSTATES`)\npub const NUMSTATES: usize = %d;\n" % len(states))
    out.append(enum_block("/// (`statenum_t`)", "StateNum", zip(states, variants(states))))

    out.append(
        enum_block(
            "\n/// (`state_t.action`) — see module docs. `None` is the\n/// original's `{NULL}`.",
            "StateAction",
            [("NULL", "None")] + list(zip(actions, variants(actions))),
        )
    )

    out.append(
        """
/// (`state_t`)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct State {
    pub sprite: SpriteNum,
    /// Frame number, possibly ORed with `FF_FULLBRIGHT`.
    pub frame: i32,
    /// Duration in tics, `-1` for forever.
    pub tics: i32,
    pub action: StateAction,
    pub nextstate: StateNum,
    pub misc1: i32,
    pub misc2: i32,
}

/// (`states[NUMSTATES]`) — indexed by [`StateNum`].
#[rustfmt::skip]
pub static STATES: [State; NUMSTATES] = ["""
    )
    for spr, frame, tics, action, nxt, m1, m2, name in state_rows:
        act = "None" if action == "NULL" else camel(action)
        out.append(
            "    State { sprite: SpriteNum::%s, frame: %s, tics: %s, action: StateAction::%s, nextstate: StateNum::%s, misc1: %s, misc2: %s }, // %s"
            % (camel(spr), frame, tics, act, camel(nxt), m1, m2, name)
        )
    out.append("];\n")

    out.append("/// (`NUMMOBJTYPES`)\npub const NUMMOBJTYPES: usize = %d;\n" % len(mobjtypes))
    out.append(enum_block("/// (`mobjtype_t`)", "MobjType", zip(mobjtypes, variants(mobjtypes))))

    mt_variants = variants(mobjtypes)
    out.append(
        "\nimpl MobjType {\n"
        "    /// The `MobjType` whose `mobjinfo[]` index (i.e. declaration\n"
        "    /// order, matching `mobjtype_t`'s values in the original) is\n"
        "    /// `i` — the safe inverse of `as usize`, for callers that find a\n"
        "    /// type by scanning `MOBJINFO` (e.g. `P_SpawnMapThing`'s\n"
        "    /// doomednum lookup) and need the enum back.\n"
        "    pub fn from_index(i: usize) -> Option<MobjType> {\n"
        "        Some(match i {"
    )
    for i, v in enumerate(mt_variants):
        out.append("            %d => MobjType::%s," % (i, v))
    out.append("            _ => return None,\n        })\n    }\n}")

    out.append(
        """
/// (`mobjinfo_t`)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MobjInfo {
    /// Editor thing number (THINGS lump `type`), `-1` if not placeable.
    pub doomednum: i32,
    pub spawnstate: StateNum,
    pub spawnhealth: i32,
    pub seestate: StateNum,
    pub seesound: Sfx,
    pub reactiontime: i32,
    pub attacksound: Sfx,
    pub painstate: StateNum,
    pub painchance: i32,
    pub painsound: Sfx,
    pub meleestate: StateNum,
    pub missilestate: StateNum,
    pub deathstate: StateNum,
    pub xdeathstate: StateNum,
    pub deathsound: Sfx,
    pub speed: Fixed,
    pub radius: Fixed,
    pub height: Fixed,
    pub mass: i32,
    pub damage: i32,
    pub activesound: Sfx,
    /// See [`mobj_flag`].
    pub flags: i32,
    pub raisestate: StateNum,
}

/// (`mobjinfo[NUMMOBJTYPES]`) — indexed by [`MobjType`].
pub static MOBJINFO: [MobjInfo; NUMMOBJTYPES] = ["""
    )
    for mt, vals in infos:
        out.append("    // %s" % mt)
        out.append("    MobjInfo {")
        for f in fields:
            out.append("        %s: %s," % (f, tr(f, vals[f])))
        out.append("    },")
    out.append("];\n")
    return "\n".join(out) + "\n"


def main():
    sounds, sfx = gen_sounds()
    info = gen_info(sfx)
    for name, text in (("sounds.rs", sounds), ("info.rs", info)):
        path = os.path.join(ROOT, "src", name)
        with open(path, "w") as f:
            f.write(text)
        # Keep the checked-in file identical to what `cargo fmt` wants.
        subprocess.run(["rustfmt", "--edition", "2021", path], check=True)
        print("wrote", path)


if __name__ == "__main__":
    main()
