#!/usr/bin/env python3
"""Generates src/hu_tables.rs (the shift/keymap tables of hu_stuff.c).

Usage: tools/gen_hu_tables.py [path/to/DoomMetal/src]
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "..", "DoomMetal", "src")

text = open(os.path.join(SRC, "hu_stuff.c")).read()
text = re.sub(r"//[^\n]*", "", text)
TOKEN = re.compile(r"'(?:\\.|[^'\\])'|\d+")


def arr(name):
    m = re.search(re.escape(name) + r"\s*(?:\[\s*\d*\s*\])?\s*=\s*\{(.*?)\};", text, re.S)
    out = []
    for t in TOKEN.findall(m.group(1)):
        if t.startswith("'"):
            v = t[1:-1]
            out.append(ord(v[1]) if v.startswith("\\") else ord(v))
        else:
            out.append(int(t))
    assert len(out) == 128, (name, len(out))
    return out


def rust(name, doc, values):
    rows = []
    for i in range(0, 128, 16):
        rows.append("    " + ", ".join(str(v) for v in values[i : i + 16]) + ",")
    return "/// %s\npub static %s: [u8; 128] = [\n%s\n];\n" % (doc, name, "\n".join(rows))


def names(name, count):
    m = re.search(re.escape(name) + r"\s*\[\s*\]\s*=\s*\{(.*?)\};", text, re.S)
    toks = [t.strip() for t in m.group(1).split(",") if t.strip()]
    assert len(toks) == count, (name, len(toks))
    lines = []
    for t in toks:
        lines.append("    " + ('"%s",' % t.strip('"') if t.startswith('"') else "crate::d_englsh::%s," % t))
    return "\n".join(lines)


def names_table(rust_name, c_name, count, doc):
    return "/// %s\npub static %s: [&str; %d] = [\n%s\n];\n" % (
        doc, rust_name, count, names(c_name, count))


out = (
    "// GENERATED by tools/gen_hu_tables.py from the original hu_stuff.c — do not edit by hand.\n\n"
    "//! The shift/keymap tables of `hu_stuff.c`.\n\n"
    + rust("FRENCH_SHIFTXFORM", "`french_shiftxform[]`.", arr("french_shiftxform"))
    + "\n"
    + rust("ENGLISH_SHIFTXFORM", "`english_shiftxform[]`.", arr("english_shiftxform"))
    + "\n"
    + rust("FRENCH_KEYMAP", "`frenchKeyMap[128]`.", arr("frenchKeyMap"))
    + "\n"
    + names_table("MAPNAMES", "mapnames", 45, "`mapnames[]`: DOOM shareware/registered/retail (Ultimate) names.")
    + "\n"
    + names_table("MAPNAMES2", "mapnames2", 32, "`mapnames2[]`: DOOM 2 map names.")
    + "\n"
    + names_table("MAPNAMESP", "mapnamesp", 32, "`mapnamesp[]`: Plutonia WAD map names.")
    + "\n"
    + names_table("MAPNAMEST", "mapnamest", 32, "`mapnamest[]`: TNT WAD map names.")
)
path = os.path.join(ROOT, "src", "hu_tables.rs")
open(path, "w").write(out)
subprocess.run(["rustfmt", "--edition", "2021", path], check=True)
print("wrote", path)
