//-----------------------------------------------------------------------------
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//  all external data is defined here
//  most of the data is loaded into different structures at run time
//  some internal structures shared by many modules are here
//
//-----------------------------------------------------------------------------

//! Rust port of `doomdata.h`.
//!
//! All external data is defined here. Most of the data is loaded into
//! different structures at run time; some internal structures shared by
//! many modules are here. These are the persistent, on-disk WAD map lump
//! formats plus a couple of related bit-flag constants.

use crate::doomtype::Byte;

/// Lump order in a map WAD: each map needs a couple of lumps to provide
/// a complete scene geometry description.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum MapLump {
    /// A separator, name, ExMx or MAPxx.
    Label = 0,
    /// Monsters, items..
    Things,
    /// LineDefs, from editing.
    Linedefs,
    /// SideDefs, from editing.
    Sidedefs,
    /// Vertices, edited and BSP splits generated.
    Vertexes,
    /// LineSegs, from LineDefs split by BSP.
    Segs,
    /// SubSectors, list of LineSegs.
    Ssectors,
    /// BSP nodes.
    Nodes,
    /// Sectors, from editing.
    Sectors,
    /// LUT, sector-sector visibility.
    Reject,
    /// LUT, motion clipping, walls/grid element.
    Blockmap,
}

/// A single vertex (`mapvertex_t`), as stored in a WAD.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
#[repr(C)]
pub struct MapVertex {
    pub x: i16,
    pub y: i16,
}

/// A SideDef, defining the visual appearance of a wall, by setting
/// textures and offsets (`mapsidedef_t`), as stored in a WAD.
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct MapSidedef {
    pub textureoffset: i16,
    pub rowoffset: i16,
    pub toptexture: [u8; 8],
    pub bottomtexture: [u8; 8],
    pub midtexture: [u8; 8],
    /// Front sector, towards viewer.
    pub sector: i16,
}

/// A LineDef, as used for editing, and as input to the BSP builder
/// (`maplinedef_t`), as stored in a WAD.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
#[repr(C)]
pub struct MapLinedef {
    pub v1: i16,
    pub v2: i16,
    pub flags: i16,
    pub special: i16,
    pub tag: i16,
    /// `sidenum[1]` will be -1 if one sided.
    pub sidenum: [i16; 2],
}

// LineDef attributes.

/// Solid, is an obstacle (`ML_BLOCKING`).
pub const ML_BLOCKING: i16 = 1;
/// Blocks monsters only (`ML_BLOCKMONSTERS`).
pub const ML_BLOCKMONSTERS: i16 = 2;
/// Backside will not be present at all if not two sided (`ML_TWOSIDED`).
pub const ML_TWOSIDED: i16 = 4;

// If a texture is pegged, the texture will have the end exposed to air
// held constant at the top or bottom of the texture (stairs or pulled
// down things) and will move with a height change of one of the
// neighbor sectors. Unpegged textures always have the first row of the
// texture at the top pixel of the line for both top and bottom textures
// (use next to windows).

/// Upper texture unpegged (`ML_DONTPEGTOP`).
pub const ML_DONTPEGTOP: i16 = 8;
/// Lower texture unpegged (`ML_DONTPEGBOTTOM`).
pub const ML_DONTPEGBOTTOM: i16 = 16;
/// In AutoMap: don't map as two sided: IT'S A SECRET! (`ML_SECRET`)
pub const ML_SECRET: i16 = 32;
/// Sound rendering: don't let sound cross two of these (`ML_SOUNDBLOCK`).
pub const ML_SOUNDBLOCK: i16 = 64;
/// Don't draw on the automap at all (`ML_DONTDRAW`).
pub const ML_DONTDRAW: i16 = 128;
/// Set if already seen, thus drawn in automap (`ML_MAPPED`).
pub const ML_MAPPED: i16 = 256;

/// Sector definition, from editing (`mapsector_t`), as stored in a WAD.
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct MapSector {
    pub floorheight: i16,
    pub ceilingheight: i16,
    pub floorpic: [u8; 8],
    pub ceilingpic: [u8; 8],
    pub lightlevel: i16,
    pub special: i16,
    pub tag: i16,
}

/// SubSector, as generated by BSP (`mapsubsector_t`), as stored in a
/// WAD.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
#[repr(C)]
pub struct MapSubsector {
    pub numsegs: i16,
    /// Index of first one, segs are stored sequentially.
    pub firstseg: i16,
}

/// LineSeg, generated by splitting LineDefs using partition lines
/// selected by the BSP builder (`mapseg_t`), as stored in a WAD.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
#[repr(C)]
pub struct MapSeg {
    pub v1: i16,
    pub v2: i16,
    pub angle: i16,
    pub linedef: i16,
    pub side: i16,
    pub offset: i16,
}

/// Indicate a leaf (`NF_SUBSECTOR`).
pub const NF_SUBSECTOR: u16 = 0x8000;

/// BSP node structure (`mapnode_t`), as stored in a WAD.
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct MapNode {
    /// Partition line from (x,y) to (x+dx,y+dy).
    pub x: i16,
    pub y: i16,
    pub dx: i16,
    pub dy: i16,
    /// Bounding box for each child, clip against view frustum.
    pub bbox: [[i16; 4]; 2],
    /// If `NF_SUBSECTOR` its a subsector, else it's a node of another
    /// subtree.
    pub children: [u16; 2],
}

/// Thing definition, position, orientation and type, plus
/// skill/visibility flags and attributes (`mapthing_t`), as stored in a
/// WAD.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
#[repr(C)]
pub struct MapThing {
    pub x: i16,
    pub y: i16,
    pub angle: i16,
    pub thing_type: i16,
    pub options: i16,
}

/// Byte-string convenience alias, documenting where a field is really a
/// fixed-size (non-necessarily-nul-terminated) ASCII name, as in the
/// original's `char toptexture[8]` etc. fields.
pub type Name8 = [Byte; 8];

#[cfg(test)]
mod tests {
    use super::*;
    use std::mem::size_of;

    #[test]
    fn maplump_values_match_original_enum_order() {
        assert_eq!(MapLump::Label as i32, 0);
        assert_eq!(MapLump::Things as i32, 1);
        assert_eq!(MapLump::Blockmap as i32, 10);
    }

    #[test]
    fn linedef_flag_values_match_original() {
        assert_eq!(ML_BLOCKING, 1);
        assert_eq!(ML_BLOCKMONSTERS, 2);
        assert_eq!(ML_TWOSIDED, 4);
        assert_eq!(ML_DONTPEGTOP, 8);
        assert_eq!(ML_DONTPEGBOTTOM, 16);
        assert_eq!(ML_SECRET, 32);
        assert_eq!(ML_SOUNDBLOCK, 64);
        assert_eq!(ML_DONTDRAW, 128);
        assert_eq!(ML_MAPPED, 256);
    }

    #[test]
    fn nf_subsector_matches_original() {
        assert_eq!(NF_SUBSECTOR, 0x8000);
    }

    #[test]
    fn wad_struct_sizes_match_c_on_disk_layout() {
        // These sizes matter for real: w_wad's future lump reader will
        // transmute/parse raw WAD bytes into these structs, so their
        // on-disk (packed, no padding) size must match the C structs
        // exactly. All fields are i16/u16 (2-byte aligned), so #[repr(C)]
        // naturally has no padding here — asserted explicitly so a
        // future field reordering that broke this would fail loudly.
        assert_eq!(size_of::<MapVertex>(), 4);
        assert_eq!(size_of::<MapLinedef>(), 14);
        assert_eq!(size_of::<MapSidedef>(), 30);
        assert_eq!(size_of::<MapSector>(), 26);
        assert_eq!(size_of::<MapSubsector>(), 4);
        assert_eq!(size_of::<MapSeg>(), 12);
        assert_eq!(size_of::<MapNode>(), 28);
        assert_eq!(size_of::<MapThing>(), 10);
    }
}
