//-----------------------------------------------------------------------------
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:  Heads-up displays
//
//-----------------------------------------------------------------------------

// GENERATED by tools/gen_hu_tables.py from the original hu_stuff.c — do not edit by hand.

//! The shift/keymap tables of `hu_stuff.c`.

/// `french_shiftxform[]`.
pub static FRENCH_SHIFTXFORM: [u8; 128] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 34, 40, 41, 42, 43, 63, 95, 62, 63, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 47, 46, 60, 43, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 33, 93, 34, 95, 39, 65,
    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
    90, 123, 124, 125, 126, 127,
];

/// `english_shiftxform[]`.
pub static ENGLISH_SHIFTXFORM: [u8; 128] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 34, 40, 41, 42, 43, 60, 95, 62, 63, 41, 33,
    64, 35, 36, 37, 94, 38, 42, 40, 58, 58, 60, 43, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 33, 93, 34, 95, 39, 65,
    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
    90, 123, 124, 125, 126, 127,
];

/// `frenchKeyMap[128]`.
pub static FRENCH_KEYMAP: [u8; 128] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 37, 40, 41, 42, 43, 59, 45, 58, 33, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 58, 77, 60, 61, 62, 63, 64, 81, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 44, 78, 79, 80, 65, 82, 83, 84, 85, 86, 90, 88, 89, 87, 94, 92, 36, 94, 95, 64, 81,
    66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 44, 78, 79, 80, 65, 82, 83, 84, 85, 86, 90, 88, 89,
    87, 94, 92, 36, 94, 127,
];

/// `mapnames[]`: DOOM shareware/registered/retail (Ultimate) names.
pub static MAPNAMES: [&str; 45] = [
    crate::d_englsh::HUSTR_E1M1,
    crate::d_englsh::HUSTR_E1M2,
    crate::d_englsh::HUSTR_E1M3,
    crate::d_englsh::HUSTR_E1M4,
    crate::d_englsh::HUSTR_E1M5,
    crate::d_englsh::HUSTR_E1M6,
    crate::d_englsh::HUSTR_E1M7,
    crate::d_englsh::HUSTR_E1M8,
    crate::d_englsh::HUSTR_E1M9,
    crate::d_englsh::HUSTR_E2M1,
    crate::d_englsh::HUSTR_E2M2,
    crate::d_englsh::HUSTR_E2M3,
    crate::d_englsh::HUSTR_E2M4,
    crate::d_englsh::HUSTR_E2M5,
    crate::d_englsh::HUSTR_E2M6,
    crate::d_englsh::HUSTR_E2M7,
    crate::d_englsh::HUSTR_E2M8,
    crate::d_englsh::HUSTR_E2M9,
    crate::d_englsh::HUSTR_E3M1,
    crate::d_englsh::HUSTR_E3M2,
    crate::d_englsh::HUSTR_E3M3,
    crate::d_englsh::HUSTR_E3M4,
    crate::d_englsh::HUSTR_E3M5,
    crate::d_englsh::HUSTR_E3M6,
    crate::d_englsh::HUSTR_E3M7,
    crate::d_englsh::HUSTR_E3M8,
    crate::d_englsh::HUSTR_E3M9,
    crate::d_englsh::HUSTR_E4M1,
    crate::d_englsh::HUSTR_E4M2,
    crate::d_englsh::HUSTR_E4M3,
    crate::d_englsh::HUSTR_E4M4,
    crate::d_englsh::HUSTR_E4M5,
    crate::d_englsh::HUSTR_E4M6,
    crate::d_englsh::HUSTR_E4M7,
    crate::d_englsh::HUSTR_E4M8,
    crate::d_englsh::HUSTR_E4M9,
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
    "NEWLEVEL",
];

/// `mapnames2[]`: DOOM 2 map names.
pub static MAPNAMES2: [&str; 32] = [
    crate::d_englsh::HUSTR_1,
    crate::d_englsh::HUSTR_2,
    crate::d_englsh::HUSTR_3,
    crate::d_englsh::HUSTR_4,
    crate::d_englsh::HUSTR_5,
    crate::d_englsh::HUSTR_6,
    crate::d_englsh::HUSTR_7,
    crate::d_englsh::HUSTR_8,
    crate::d_englsh::HUSTR_9,
    crate::d_englsh::HUSTR_10,
    crate::d_englsh::HUSTR_11,
    crate::d_englsh::HUSTR_12,
    crate::d_englsh::HUSTR_13,
    crate::d_englsh::HUSTR_14,
    crate::d_englsh::HUSTR_15,
    crate::d_englsh::HUSTR_16,
    crate::d_englsh::HUSTR_17,
    crate::d_englsh::HUSTR_18,
    crate::d_englsh::HUSTR_19,
    crate::d_englsh::HUSTR_20,
    crate::d_englsh::HUSTR_21,
    crate::d_englsh::HUSTR_22,
    crate::d_englsh::HUSTR_23,
    crate::d_englsh::HUSTR_24,
    crate::d_englsh::HUSTR_25,
    crate::d_englsh::HUSTR_26,
    crate::d_englsh::HUSTR_27,
    crate::d_englsh::HUSTR_28,
    crate::d_englsh::HUSTR_29,
    crate::d_englsh::HUSTR_30,
    crate::d_englsh::HUSTR_31,
    crate::d_englsh::HUSTR_32,
];

/// `mapnamesp[]`: Plutonia WAD map names.
pub static MAPNAMESP: [&str; 32] = [
    crate::d_englsh::PHUSTR_1,
    crate::d_englsh::PHUSTR_2,
    crate::d_englsh::PHUSTR_3,
    crate::d_englsh::PHUSTR_4,
    crate::d_englsh::PHUSTR_5,
    crate::d_englsh::PHUSTR_6,
    crate::d_englsh::PHUSTR_7,
    crate::d_englsh::PHUSTR_8,
    crate::d_englsh::PHUSTR_9,
    crate::d_englsh::PHUSTR_10,
    crate::d_englsh::PHUSTR_11,
    crate::d_englsh::PHUSTR_12,
    crate::d_englsh::PHUSTR_13,
    crate::d_englsh::PHUSTR_14,
    crate::d_englsh::PHUSTR_15,
    crate::d_englsh::PHUSTR_16,
    crate::d_englsh::PHUSTR_17,
    crate::d_englsh::PHUSTR_18,
    crate::d_englsh::PHUSTR_19,
    crate::d_englsh::PHUSTR_20,
    crate::d_englsh::PHUSTR_21,
    crate::d_englsh::PHUSTR_22,
    crate::d_englsh::PHUSTR_23,
    crate::d_englsh::PHUSTR_24,
    crate::d_englsh::PHUSTR_25,
    crate::d_englsh::PHUSTR_26,
    crate::d_englsh::PHUSTR_27,
    crate::d_englsh::PHUSTR_28,
    crate::d_englsh::PHUSTR_29,
    crate::d_englsh::PHUSTR_30,
    crate::d_englsh::PHUSTR_31,
    crate::d_englsh::PHUSTR_32,
];

/// `mapnamest[]`: TNT WAD map names.
pub static MAPNAMEST: [&str; 32] = [
    crate::d_englsh::THUSTR_1,
    crate::d_englsh::THUSTR_2,
    crate::d_englsh::THUSTR_3,
    crate::d_englsh::THUSTR_4,
    crate::d_englsh::THUSTR_5,
    crate::d_englsh::THUSTR_6,
    crate::d_englsh::THUSTR_7,
    crate::d_englsh::THUSTR_8,
    crate::d_englsh::THUSTR_9,
    crate::d_englsh::THUSTR_10,
    crate::d_englsh::THUSTR_11,
    crate::d_englsh::THUSTR_12,
    crate::d_englsh::THUSTR_13,
    crate::d_englsh::THUSTR_14,
    crate::d_englsh::THUSTR_15,
    crate::d_englsh::THUSTR_16,
    crate::d_englsh::THUSTR_17,
    crate::d_englsh::THUSTR_18,
    crate::d_englsh::THUSTR_19,
    crate::d_englsh::THUSTR_20,
    crate::d_englsh::THUSTR_21,
    crate::d_englsh::THUSTR_22,
    crate::d_englsh::THUSTR_23,
    crate::d_englsh::THUSTR_24,
    crate::d_englsh::THUSTR_25,
    crate::d_englsh::THUSTR_26,
    crate::d_englsh::THUSTR_27,
    crate::d_englsh::THUSTR_28,
    crate::d_englsh::THUSTR_29,
    crate::d_englsh::THUSTR_30,
    crate::d_englsh::THUSTR_31,
    crate::d_englsh::THUSTR_32,
];
