//-----------------------------------------------------------------------------
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//	Created by a sound utility.
//	Kept as a sample, DOOM2 sounds.
//
//-----------------------------------------------------------------------------

// GENERATED by tools/gen_info.py from the original sounds.h — do not edit by hand.

//! Port of `sounds.h` (enums only). Created by BIFFO — the
//! original's own description of `sounds.h`.
//!
//! # Scope
//!
//! `musicenum_t`/`sfxenum_t` (which `info.rs`'s mobj table refers to)
//! plus the static `S_sfx`/`S_music` tables from `sounds.c`.
//!
//! Variants keep the original's `mus_`/`sfx_` prefixes, same convention
//! as `doomdef.rs`'s enums.

/// (`NUMMUSIC`)
pub const NUMMUSIC: usize = 68;

/// Identifiers for all music in game (`musicenum_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(clippy::enum_variant_names)]
pub enum MusicEnum {
    /// `mus_None`
    MusNone,
    /// `mus_e1m1`
    MusE1m1,
    /// `mus_e1m2`
    MusE1m2,
    /// `mus_e1m3`
    MusE1m3,
    /// `mus_e1m4`
    MusE1m4,
    /// `mus_e1m5`
    MusE1m5,
    /// `mus_e1m6`
    MusE1m6,
    /// `mus_e1m7`
    MusE1m7,
    /// `mus_e1m8`
    MusE1m8,
    /// `mus_e1m9`
    MusE1m9,
    /// `mus_e2m1`
    MusE2m1,
    /// `mus_e2m2`
    MusE2m2,
    /// `mus_e2m3`
    MusE2m3,
    /// `mus_e2m4`
    MusE2m4,
    /// `mus_e2m5`
    MusE2m5,
    /// `mus_e2m6`
    MusE2m6,
    /// `mus_e2m7`
    MusE2m7,
    /// `mus_e2m8`
    MusE2m8,
    /// `mus_e2m9`
    MusE2m9,
    /// `mus_e3m1`
    MusE3m1,
    /// `mus_e3m2`
    MusE3m2,
    /// `mus_e3m3`
    MusE3m3,
    /// `mus_e3m4`
    MusE3m4,
    /// `mus_e3m5`
    MusE3m5,
    /// `mus_e3m6`
    MusE3m6,
    /// `mus_e3m7`
    MusE3m7,
    /// `mus_e3m8`
    MusE3m8,
    /// `mus_e3m9`
    MusE3m9,
    /// `mus_inter`
    MusInter,
    /// `mus_intro`
    MusIntro,
    /// `mus_bunny`
    MusBunny,
    /// `mus_victor`
    MusVictor,
    /// `mus_introa`
    MusIntroa,
    /// `mus_runnin`
    MusRunnin,
    /// `mus_stalks`
    MusStalks,
    /// `mus_countd`
    MusCountd,
    /// `mus_betwee`
    MusBetwee,
    /// `mus_doom`
    MusDoom,
    /// `mus_the_da`
    MusTheDa,
    /// `mus_shawn`
    MusShawn,
    /// `mus_ddtblu`
    MusDdtblu,
    /// `mus_in_cit`
    MusInCit,
    /// `mus_dead`
    MusDead,
    /// `mus_stlks2`
    MusStlks2,
    /// `mus_theda2`
    MusTheda2,
    /// `mus_doom2`
    MusDoom2,
    /// `mus_ddtbl2`
    MusDdtbl2,
    /// `mus_runni2`
    MusRunni2,
    /// `mus_dead2`
    MusDead2,
    /// `mus_stlks3`
    MusStlks3,
    /// `mus_romero`
    MusRomero,
    /// `mus_shawn2`
    MusShawn2,
    /// `mus_messag`
    MusMessag,
    /// `mus_count2`
    MusCount2,
    /// `mus_ddtbl3`
    MusDdtbl3,
    /// `mus_ampie`
    MusAmpie,
    /// `mus_theda3`
    MusTheda3,
    /// `mus_adrian`
    MusAdrian,
    /// `mus_messg2`
    MusMessg2,
    /// `mus_romer2`
    MusRomer2,
    /// `mus_tense`
    MusTense,
    /// `mus_shawn3`
    MusShawn3,
    /// `mus_openin`
    MusOpenin,
    /// `mus_evil`
    MusEvil,
    /// `mus_ultima`
    MusUltima,
    /// `mus_read_m`
    MusReadM,
    /// `mus_dm2ttl`
    MusDm2ttl,
    /// `mus_dm2int`
    MusDm2int,
}

/// (`NUMSFX`)
pub const NUMSFX: usize = 109;

/// Identifiers for all sfx in game (`sfxenum_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(clippy::enum_variant_names)]
pub enum Sfx {
    /// `sfx_None`
    SfxNone,
    /// `sfx_pistol`
    SfxPistol,
    /// `sfx_shotgn`
    SfxShotgn,
    /// `sfx_sgcock`
    SfxSgcock,
    /// `sfx_dshtgn`
    SfxDshtgn,
    /// `sfx_dbopn`
    SfxDbopn,
    /// `sfx_dbcls`
    SfxDbcls,
    /// `sfx_dbload`
    SfxDbload,
    /// `sfx_plasma`
    SfxPlasma,
    /// `sfx_bfg`
    SfxBfg,
    /// `sfx_sawup`
    SfxSawup,
    /// `sfx_sawidl`
    SfxSawidl,
    /// `sfx_sawful`
    SfxSawful,
    /// `sfx_sawhit`
    SfxSawhit,
    /// `sfx_rlaunc`
    SfxRlaunc,
    /// `sfx_rxplod`
    SfxRxplod,
    /// `sfx_firsht`
    SfxFirsht,
    /// `sfx_firxpl`
    SfxFirxpl,
    /// `sfx_pstart`
    SfxPstart,
    /// `sfx_pstop`
    SfxPstop,
    /// `sfx_doropn`
    SfxDoropn,
    /// `sfx_dorcls`
    SfxDorcls,
    /// `sfx_stnmov`
    SfxStnmov,
    /// `sfx_swtchn`
    SfxSwtchn,
    /// `sfx_swtchx`
    SfxSwtchx,
    /// `sfx_plpain`
    SfxPlpain,
    /// `sfx_dmpain`
    SfxDmpain,
    /// `sfx_popain`
    SfxPopain,
    /// `sfx_vipain`
    SfxVipain,
    /// `sfx_mnpain`
    SfxMnpain,
    /// `sfx_pepain`
    SfxPepain,
    /// `sfx_slop`
    SfxSlop,
    /// `sfx_itemup`
    SfxItemup,
    /// `sfx_wpnup`
    SfxWpnup,
    /// `sfx_oof`
    SfxOof,
    /// `sfx_telept`
    SfxTelept,
    /// `sfx_posit1`
    SfxPosit1,
    /// `sfx_posit2`
    SfxPosit2,
    /// `sfx_posit3`
    SfxPosit3,
    /// `sfx_bgsit1`
    SfxBgsit1,
    /// `sfx_bgsit2`
    SfxBgsit2,
    /// `sfx_sgtsit`
    SfxSgtsit,
    /// `sfx_cacsit`
    SfxCacsit,
    /// `sfx_brssit`
    SfxBrssit,
    /// `sfx_cybsit`
    SfxCybsit,
    /// `sfx_spisit`
    SfxSpisit,
    /// `sfx_bspsit`
    SfxBspsit,
    /// `sfx_kntsit`
    SfxKntsit,
    /// `sfx_vilsit`
    SfxVilsit,
    /// `sfx_mansit`
    SfxMansit,
    /// `sfx_pesit`
    SfxPesit,
    /// `sfx_sklatk`
    SfxSklatk,
    /// `sfx_sgtatk`
    SfxSgtatk,
    /// `sfx_skepch`
    SfxSkepch,
    /// `sfx_vilatk`
    SfxVilatk,
    /// `sfx_claw`
    SfxClaw,
    /// `sfx_skeswg`
    SfxSkeswg,
    /// `sfx_pldeth`
    SfxPldeth,
    /// `sfx_pdiehi`
    SfxPdiehi,
    /// `sfx_podth1`
    SfxPodth1,
    /// `sfx_podth2`
    SfxPodth2,
    /// `sfx_podth3`
    SfxPodth3,
    /// `sfx_bgdth1`
    SfxBgdth1,
    /// `sfx_bgdth2`
    SfxBgdth2,
    /// `sfx_sgtdth`
    SfxSgtdth,
    /// `sfx_cacdth`
    SfxCacdth,
    /// `sfx_skldth`
    SfxSkldth,
    /// `sfx_brsdth`
    SfxBrsdth,
    /// `sfx_cybdth`
    SfxCybdth,
    /// `sfx_spidth`
    SfxSpidth,
    /// `sfx_bspdth`
    SfxBspdth,
    /// `sfx_vildth`
    SfxVildth,
    /// `sfx_kntdth`
    SfxKntdth,
    /// `sfx_pedth`
    SfxPedth,
    /// `sfx_skedth`
    SfxSkedth,
    /// `sfx_posact`
    SfxPosact,
    /// `sfx_bgact`
    SfxBgact,
    /// `sfx_dmact`
    SfxDmact,
    /// `sfx_bspact`
    SfxBspact,
    /// `sfx_bspwlk`
    SfxBspwlk,
    /// `sfx_vilact`
    SfxVilact,
    /// `sfx_noway`
    SfxNoway,
    /// `sfx_barexp`
    SfxBarexp,
    /// `sfx_punch`
    SfxPunch,
    /// `sfx_hoof`
    SfxHoof,
    /// `sfx_metal`
    SfxMetal,
    /// `sfx_chgun`
    SfxChgun,
    /// `sfx_tink`
    SfxTink,
    /// `sfx_bdopn`
    SfxBdopn,
    /// `sfx_bdcls`
    SfxBdcls,
    /// `sfx_itmbk`
    SfxItmbk,
    /// `sfx_flame`
    SfxFlame,
    /// `sfx_flamst`
    SfxFlamst,
    /// `sfx_getpow`
    SfxGetpow,
    /// `sfx_bospit`
    SfxBospit,
    /// `sfx_boscub`
    SfxBoscub,
    /// `sfx_bossit`
    SfxBossit,
    /// `sfx_bospn`
    SfxBospn,
    /// `sfx_bosdth`
    SfxBosdth,
    /// `sfx_manatk`
    SfxManatk,
    /// `sfx_mandth`
    SfxMandth,
    /// `sfx_sssit`
    SfxSssit,
    /// `sfx_ssdth`
    SfxSsdth,
    /// `sfx_keenpn`
    SfxKeenpn,
    /// `sfx_keendt`
    SfxKeendt,
    /// `sfx_skeact`
    SfxSkeact,
    /// `sfx_skesit`
    SfxSkesit,
    /// `sfx_skeatk`
    SfxSkeatk,
    /// `sfx_radio`
    SfxRadio,
}

impl Sfx {
    /// Every sfx in enum order, so `sfx_posit1 + n`-style arithmetic can
    /// be done as `Sfx::from_index(Sfx::SfxPosit1 as usize + n)`.
    pub const ALL: [Sfx; NUMSFX] = [
        Sfx::SfxNone,
        Sfx::SfxPistol,
        Sfx::SfxShotgn,
        Sfx::SfxSgcock,
        Sfx::SfxDshtgn,
        Sfx::SfxDbopn,
        Sfx::SfxDbcls,
        Sfx::SfxDbload,
        Sfx::SfxPlasma,
        Sfx::SfxBfg,
        Sfx::SfxSawup,
        Sfx::SfxSawidl,
        Sfx::SfxSawful,
        Sfx::SfxSawhit,
        Sfx::SfxRlaunc,
        Sfx::SfxRxplod,
        Sfx::SfxFirsht,
        Sfx::SfxFirxpl,
        Sfx::SfxPstart,
        Sfx::SfxPstop,
        Sfx::SfxDoropn,
        Sfx::SfxDorcls,
        Sfx::SfxStnmov,
        Sfx::SfxSwtchn,
        Sfx::SfxSwtchx,
        Sfx::SfxPlpain,
        Sfx::SfxDmpain,
        Sfx::SfxPopain,
        Sfx::SfxVipain,
        Sfx::SfxMnpain,
        Sfx::SfxPepain,
        Sfx::SfxSlop,
        Sfx::SfxItemup,
        Sfx::SfxWpnup,
        Sfx::SfxOof,
        Sfx::SfxTelept,
        Sfx::SfxPosit1,
        Sfx::SfxPosit2,
        Sfx::SfxPosit3,
        Sfx::SfxBgsit1,
        Sfx::SfxBgsit2,
        Sfx::SfxSgtsit,
        Sfx::SfxCacsit,
        Sfx::SfxBrssit,
        Sfx::SfxCybsit,
        Sfx::SfxSpisit,
        Sfx::SfxBspsit,
        Sfx::SfxKntsit,
        Sfx::SfxVilsit,
        Sfx::SfxMansit,
        Sfx::SfxPesit,
        Sfx::SfxSklatk,
        Sfx::SfxSgtatk,
        Sfx::SfxSkepch,
        Sfx::SfxVilatk,
        Sfx::SfxClaw,
        Sfx::SfxSkeswg,
        Sfx::SfxPldeth,
        Sfx::SfxPdiehi,
        Sfx::SfxPodth1,
        Sfx::SfxPodth2,
        Sfx::SfxPodth3,
        Sfx::SfxBgdth1,
        Sfx::SfxBgdth2,
        Sfx::SfxSgtdth,
        Sfx::SfxCacdth,
        Sfx::SfxSkldth,
        Sfx::SfxBrsdth,
        Sfx::SfxCybdth,
        Sfx::SfxSpidth,
        Sfx::SfxBspdth,
        Sfx::SfxVildth,
        Sfx::SfxKntdth,
        Sfx::SfxPedth,
        Sfx::SfxSkedth,
        Sfx::SfxPosact,
        Sfx::SfxBgact,
        Sfx::SfxDmact,
        Sfx::SfxBspact,
        Sfx::SfxBspwlk,
        Sfx::SfxVilact,
        Sfx::SfxNoway,
        Sfx::SfxBarexp,
        Sfx::SfxPunch,
        Sfx::SfxHoof,
        Sfx::SfxMetal,
        Sfx::SfxChgun,
        Sfx::SfxTink,
        Sfx::SfxBdopn,
        Sfx::SfxBdcls,
        Sfx::SfxItmbk,
        Sfx::SfxFlame,
        Sfx::SfxFlamst,
        Sfx::SfxGetpow,
        Sfx::SfxBospit,
        Sfx::SfxBoscub,
        Sfx::SfxBossit,
        Sfx::SfxBospn,
        Sfx::SfxBosdth,
        Sfx::SfxManatk,
        Sfx::SfxMandth,
        Sfx::SfxSssit,
        Sfx::SfxSsdth,
        Sfx::SfxKeenpn,
        Sfx::SfxKeendt,
        Sfx::SfxSkeact,
        Sfx::SfxSkesit,
        Sfx::SfxSkeatk,
        Sfx::SfxRadio,
    ];

    /// `sfxenum_t` from its integer value.
    pub fn from_index(i: usize) -> Sfx {
        Self::ALL[i]
    }
}

/// Static half of `sfxinfo_t` (`sounds.c`'s `S_sfx[]`). The runtime
/// fields (`data`, `usefulness`, `lumpnum`) live in `s_sound.rs`.
#[derive(Debug, Clone, Copy)]
pub struct SfxInfo {
    /// Up to 6-character name (lump is `ds<name>`).
    pub name: &'static str,
    /// Only one at a time.
    pub singularity: bool,
    pub priority: i32,
    /// Referenced sound if a link.
    pub link: Option<Sfx>,
    /// Pitch if a link.
    pub pitch: i32,
    /// Volume if a link.
    pub volume: i32,
}

/// `S_sfx[]`.
pub static S_SFX: [SfxInfo; NUMSFX] = [
    SfxInfo {
        name: "none",
        singularity: false,
        priority: 0,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pistol",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "shotgn",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sgcock",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dshtgn",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dbopn",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dbcls",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dbload",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "plasma",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bfg",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sawup",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sawidl",
        singularity: false,
        priority: 118,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sawful",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sawhit",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "rlaunc",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "rxplod",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "firsht",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "firxpl",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pstart",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pstop",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "doropn",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dorcls",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "stnmov",
        singularity: false,
        priority: 119,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "swtchn",
        singularity: false,
        priority: 78,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "swtchx",
        singularity: false,
        priority: 78,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "plpain",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dmpain",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "popain",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "vipain",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "mnpain",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pepain",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "slop",
        singularity: false,
        priority: 78,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "itemup",
        singularity: true,
        priority: 78,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "wpnup",
        singularity: true,
        priority: 78,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "oof",
        singularity: false,
        priority: 96,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "telept",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "posit1",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "posit2",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "posit3",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bgsit1",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bgsit2",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sgtsit",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "cacsit",
        singularity: true,
        priority: 98,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "brssit",
        singularity: true,
        priority: 94,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "cybsit",
        singularity: true,
        priority: 92,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "spisit",
        singularity: true,
        priority: 90,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bspsit",
        singularity: true,
        priority: 90,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "kntsit",
        singularity: true,
        priority: 90,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "vilsit",
        singularity: true,
        priority: 90,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "mansit",
        singularity: true,
        priority: 90,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pesit",
        singularity: true,
        priority: 90,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sklatk",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sgtatk",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skepch",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "vilatk",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "claw",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skeswg",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pldeth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pdiehi",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "podth1",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "podth2",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "podth3",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bgdth1",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bgdth2",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sgtdth",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "cacdth",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skldth",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "brsdth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "cybdth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "spidth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bspdth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "vildth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "kntdth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "pedth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skedth",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "posact",
        singularity: true,
        priority: 120,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bgact",
        singularity: true,
        priority: 120,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "dmact",
        singularity: true,
        priority: 120,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bspact",
        singularity: true,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bspwlk",
        singularity: true,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "vilact",
        singularity: true,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "noway",
        singularity: false,
        priority: 78,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "barexp",
        singularity: false,
        priority: 60,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "punch",
        singularity: false,
        priority: 64,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "hoof",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "metal",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "chgun",
        singularity: false,
        priority: 64,
        link: Some(Sfx::SfxPistol),
        pitch: 150,
        volume: 0,
    },
    SfxInfo {
        name: "tink",
        singularity: false,
        priority: 60,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bdopn",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bdcls",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "itmbk",
        singularity: false,
        priority: 100,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "flame",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "flamst",
        singularity: false,
        priority: 32,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "getpow",
        singularity: false,
        priority: 60,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bospit",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "boscub",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bossit",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bospn",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "bosdth",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "manatk",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "mandth",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "sssit",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "ssdth",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "keenpn",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "keendt",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skeact",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skesit",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "skeatk",
        singularity: false,
        priority: 70,
        link: None,
        pitch: -1,
        volume: -1,
    },
    SfxInfo {
        name: "radio",
        singularity: false,
        priority: 60,
        link: None,
        pitch: -1,
        volume: -1,
    },
];

/// `S_music[]`: lump name is `d_<name>`; `mus_None` has none.
pub static S_MUSIC: [Option<&str>; NUMMUSIC] = [
    None,
    Some("e1m1"),
    Some("e1m2"),
    Some("e1m3"),
    Some("e1m4"),
    Some("e1m5"),
    Some("e1m6"),
    Some("e1m7"),
    Some("e1m8"),
    Some("e1m9"),
    Some("e2m1"),
    Some("e2m2"),
    Some("e2m3"),
    Some("e2m4"),
    Some("e2m5"),
    Some("e2m6"),
    Some("e2m7"),
    Some("e2m8"),
    Some("e2m9"),
    Some("e3m1"),
    Some("e3m2"),
    Some("e3m3"),
    Some("e3m4"),
    Some("e3m5"),
    Some("e3m6"),
    Some("e3m7"),
    Some("e3m8"),
    Some("e3m9"),
    Some("inter"),
    Some("intro"),
    Some("bunny"),
    Some("victor"),
    Some("introa"),
    Some("runnin"),
    Some("stalks"),
    Some("countd"),
    Some("betwee"),
    Some("doom"),
    Some("the_da"),
    Some("shawn"),
    Some("ddtblu"),
    Some("in_cit"),
    Some("dead"),
    Some("stlks2"),
    Some("theda2"),
    Some("doom2"),
    Some("ddtbl2"),
    Some("runni2"),
    Some("dead2"),
    Some("stlks3"),
    Some("romero"),
    Some("shawn2"),
    Some("messag"),
    Some("count2"),
    Some("ddtbl3"),
    Some("ampie"),
    Some("theda3"),
    Some("adrian"),
    Some("messg2"),
    Some("romer2"),
    Some("tense"),
    Some("shawn3"),
    Some("openin"),
    Some("evil"),
    Some("ultima"),
    Some("read_m"),
    Some("dm2ttl"),
    Some("dm2int"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enum_sizes_match_original_counts() {
        assert_eq!(MusicEnum::MusNone as usize, 0);
        assert_eq!(Sfx::SfxNone as usize, 0);
        assert_eq!(Sfx::SfxRadio as usize, NUMSFX - 1);
        assert_eq!(MusicEnum::MusDm2int as usize, NUMMUSIC - 1);
    }

    #[test]
    fn sound_tables_match_sounds_c() {
        assert_eq!(S_SFX[Sfx::SfxPistol as usize].name, "pistol");
        assert_eq!(S_SFX[Sfx::SfxSawidl as usize].priority, 118);
        assert!(S_SFX[Sfx::SfxItemup as usize].singularity);
        let chgun = &S_SFX[Sfx::SfxChgun as usize];
        assert_eq!((chgun.link, chgun.pitch), (Some(Sfx::SfxPistol), 150));
        assert!(S_SFX[Sfx::SfxPistol as usize].link.is_none());
        assert_eq!(S_MUSIC[MusicEnum::MusNone as usize], None);
        assert_eq!(S_MUSIC[MusicEnum::MusE1m1 as usize], Some("e1m1"));
    }
}
